f=r"D:\workspaces\website\chinese-traditional-wear\src\pages\index.astro"
c=open(f,"r",encoding="utf-8").read()
c=c.replace("\u2019","'")
c=c.replace("\u2014"," - ")
c=c.replace("\u00b7"," · ")
c=c.replace("\u2022","•")
c=c.replace("\\u2019","'")
c=c.replace("\\u2014"," - ")
c=c.replace("\\u00b7"," · ")
c=c.replace("\\u2022","•")
c=c.replace("&middot;"," · ")
open(f,"w",encoding="utf-8",newline="\n").write(c)
print("Unicode escapes fixed")
print("Has literal \\u:", "\\u20" in c or "\\u00" in c)
